site_name: Softwareentwicklung Mobile
site_url: https://stefanhuber.github.io/softwareentwicklung-mobile/
site_author: Stefan Huber
site_description: Ergänzende Unterlagen zur Lehrveranstaltung App-zentrierte Softwareentwicklung

repo_name: stefanhuber/softwareentwicklung-mobile
repo_url: https://github.com/stefanhuber/softwareentwicklung-mobile 
edit_uri: https://github.com/stefanhuber/softwareentwicklung-mobile/edit/master/content

theme:
  name: material
  custom_dir: material
  language: de
  features:
    - tabs
  icon:
    logo: fontawesome/solid/mobile-alt

nav:
  - Home: 'index.md'
  - Tutorials:
    - Neues Projekt: 'tutorials/neues-projekt.md'
    - Apps ausführen: 'tutorials/apps-ausführen.md'
    - adb: 'tutorials/adb.md'
  - Übungen:
    - Übungsblatt 1: 'übungen/01.md'
    - Übungsblatt 2: 'übungen/02.md'
    - Übungsblatt 3: 'übungen/03.md'
    - Übungsblatt 4: 'übungen/04.md'
    - Übungsblatt 5: 'übungen/05.md'
    - Übungsblatt 6: 'übungen/06.md'
    - Übungsblatt 7: 'übungen/07.md'
    - Übungsblatt 8: 'übungen/08.md'
    #- Übungsblatt 3: 'übungen/03.md'
    #- Übungsblatt 4: 'übungen/04.md'
    #- Übungsblatt 5: 'übungen/05.md'
    #- Übungsblatt 6: 'übungen/06.md'
    
copyright: 'CC-BY-SA / Stefan Huber'

docs_dir: content
site_dir: docs

extra:
  search:
    language: de

markdown_extensions:  
- pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
- attr_list
- def_list
- markdown.extensions.admonition  
- pymdownx.superfences
